### ISSUE TITLE
Display gives complex conjugate of what it should be

### ISSUE THREAD

**Issue by dpthurst** [xaos-project/XaoS#132] opened 2020-01-22 21:22 UTC
In the display, the imaginary axis is reversed from the standard mathematical convention, and as a result everything is the complex conjugate of what it should be. This is often not noticeable, as many fractal formulas are invariant under complex conjugation. For instance, if you pick a point in the Mandelbrot set, the value of c is the conjugate of the standard choice, and then the Julia set is also drawn as its conjugate, so everything appears to work fine.

But, for instance, if you enter z^2+i as a user formula, the fractal is the mirror of what it should be. (This polynomial maps 0 -> i -> -1+i -> -i -> -1+i; in particular -1+i should be in the Julia set. But the corresponding point is visibly not in the drawn Julia set.)

**Comment by jblang** [comment] 2020-01-27 03:06
I believe this is a duplicate of #5.  I investigated but I haven't been able to find where the coordinates are being flipped in the code.

**Comment by dpthurst** [comment] 2020-02-01 04:45
Sorry, yes, I missed that, this should be merged with #5.

Wouldn't the issue be that coordinates are never flipped? By default,
screen coordinates in most frameworks have the positive x-axis
pointing to the right, and the positive y-axis pointing down. This is
the opposite of the usual mathematical conventions.

(I have not yet gotten to digging in the code.)

--Dylan

**Comment by jblang** [comment] 2020-02-01 16:26
I think you are right. Thanks for that insights. Let's continue this discussion on #5 though.

**Closed by jblang** 2020-02-01 16:26 UTC
