### ISSUE TITLE
Antialiasing filter causes segfault at resolution > 1920X1080

### ISSUE THREAD

**Issue by kl4yfd** [xaos-project/XaoS#84] opened 2016-02-17 02:37 UTC
Xaos segfaults at resolution of 1920X1200
Works properly at 1920x1080 (1080p)

Segfault happens at: anti.c line 55

While we are at it,
Can this just be extended to support 4K resolution please?

**Comment by philippeback** [comment] 2018-01-28 11:56
Yes, 4K! Where is one to look for resolution in the codebase?

**Comment by jblang** [comment] 2019-04-13 20:59
Sorry, I know it's been a long time since you opened this.  The project has been pretty dead for a while.

Was this on a binary that you compiled yourself? What version was it? It would also be helpful if you can generate a backtrace from the segfault.

I suspect that this is caused by having alloca enabled. This is a faster way to allocate memory on the stack but it is limited in the size it can handle, so high resolutions crash XaoS if it's enabled.  It was possible previously to disable this by commenting out the `#define HAVE_ALLOCA` line in aconfig.h after running `configure`, and we already did this on binaries that we built. I have just committed a change today to remove it entirely because it doesn't really improve performance and it just causes problems for people.  Without using alloca, I'm able to maximize my window without crashing on my Windows laptop which has a 4K screen.

**Comment by jblang** [comment] 2019-05-06 14:20
I'm closing this since nobody responded and I am pretty sure it was caused the alloca issue, which has been fixed.

**Closed by jblang** 2019-05-06 14:20 UTC
Labels: bug
