### ISSUE TITLE
Problems with movies made with user formulas

### ISSUE THREAD

**Issue by kovzol** [xaos-project/XaoS#124] opened 2020-01-06 21:11 UTC
There are two major problems:
1. The formula is not saved in the .xaf file.
2. The program crashes when rendering starts. The crash occurs in sffe_eval() sffe.c, line 308 (it is called by sffe_calc in docalc.h, line 228).

**Comment by jblang** [comment] 2020-01-10 02:03
This may be related to the problem that causes the crash with multi-threading and user formulas. The problem is that the user formulas use a single global uih_context and the rendering establishes a second uih_context to do the rendering, which conflicts with the already existing one for the UI.  We need to refactor some code in the formulas.cpp and docalc.h to allow passing a specific fractal context containing the formula parser instead of using a global one.

**Comment by jblang** [comment] 2020-01-11 01:19
I believe I have fixed this as part of my last commit to prevent crashing when using multiple threads.  I found where the formula number was hard coded into the condition for code that saves the user formula, and when more formulas were added, it was no longer saving the user formula because the position within the list changed.  I have confirmed It's now saving the formula and that I can render an animation.  

I did notice an issue that when multiple threads are enabled the UI is not showing any progress indication for rendering and appears to be hung, but it does still generate pngs, and after the rendering is finished it comes back to life.

Please confirm it works for you now too and I will close this out.

**Comment by kovzol** [comment] 2020-01-11 09:24
Thanks, I did some testing and everything seems to work nicely.

**Closed** 2020-01-11 16:02 UTC
Labels: bug, rendering
