### ISSUE TITLE
How to generate and save image of specific size?

### ISSUE THREAD

**Issue by PiotrNestor** [xaos-project/XaoS#161] opened 2020-06-03 07:00 UTC
How to generate and save image of specific size?

Is it possible to generate an image of a specific size?

Also when in full screen (F11) and with the command dialog: (saveimg imgname)
no image file is created.

**Comment by kanurag94** [comment] 2020-06-03 07:19
> Is it possible to generate an image of a specific size?

As far as I know this is not currently possible but is a great idea. I will try to implement this soon.

> Also when in full screen (F11) and with the command dialog: (saveimg imgname)

The correct usage is ```(saveimg "your_file_name.png")```
Thanks for pointing this out,  I will update the documentation accordingly.

Keeping this issue open for tracking **Support for manual size while exporting image**

**Comment by PiotrNestor** [comment] 2020-06-03 07:43
This is XaoS 4.0 on Windows 10. Running from an unzipped download.

Yes, this works fine: (saveimg "your_file_name.png")

But creating an xpf file and the rendering from the command-line produces nothing.
Example fract0.xpf:
```
(initstate)
(filter 'anti #t)
(palette 1 16291 0)
(formula 'octal)
(maxiter 320)
(outcoloring 6)
(incoloring 2)
(view -0.47161 -0.23858 0.50409 0.50409)
```

Command:
```
xaos -render fract0.xpf
```

Output:
Initializing

Then nothing more

**Comment by kanurag94** [comment] 2020-06-03 09:36
> But creating an xpf file and the rendering from the command-line produces nothing.

I was able to reproduce this error. PR #159 fixed this very recently. If you can build from source code, it'll work.
PS: You can use GUI meanwhile until it's included in next release.

**Comment by PiotrNestor** [comment] 2020-06-03 12:15
Yes, I've verified that '-render' works OK (on AWS Linux) when xaos is build from latest master branch.
Thanks!

**Comment by PiotrNestor** [comment] 2020-06-03 12:38
I think, there is still a problem with '-render'. It's only possible to render the default mandelbrot fractal that is loaded in xaos.

Example:
```
xaos -render  fract0.xpf -size 1920x1080 -saveimg octal.png
```
does not produce the Octal fractal

**Comment by kanurag94** [comment] 2020-06-03 12:44
The correct usage will be

```
xaos -render  path/to/fract0.xpf -size 1920x1080 -basename octal
```
This will produce a octal0000.png inside your /bin/ folder

I can confirm this works everywhere on linux. Are you suggesting this on windows? Or is the behavior same on linux?

**Comment by PiotrNestor** [comment] 2020-06-03 12:49
OK, it's just my confusion :( and mixing commands
-saveimg should be -basename as you correctly pointed out.
Still learning the command-line possibilities ....

**Comment by PiotrNestor** [comment] 2020-06-03 13:15
OK, another -render question
What's the recommended AWS GPU instance type. g2.2xlarge ? g3s.xlarge ? 
The CPU only type is just painfully slow

**Comment by PiotrNestor** [comment] 2020-06-03 14:59
I think I prefer the Linux env. Thanks for the memory config comment.

For some reason the build fails. 
```
g++ -c -pipe -ffast-math -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -D_REENTRANT -fPIC -DUSE_LONG_DOUBLE -DUSE_SFFE -DSFFE_CMPLX_GSL -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -Isrc/include -Isrc/ui -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib64/qt5/mkspecs/linux-g++ -o qrc_XaoS.o qrc_XaoS.cpp
g++ -pipe -ffast-math -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
/usr/lib64/qt5/bin/moc -DUSE_LONG_DOUBLE -DUSE_SFFE -DSFFE_CMPLX_GSL -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/ec2-user/xaos -I/home/ec2-user/xaos/src/include -I/home/ec2-user/xaos/src/ui -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/aarch64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/aarch64-redhat-linux/7/include -I/usr/local/include -I/usr/include src/ui/mainwindow.h -o moc_mainwindow.cpp
usr/include/c++/7/bits/stl_relops.:67: Parse error at "std"
make: *** [moc_mainwindow.cpp] Error 1
```

**Comment by kanurag94** [comment] 2020-06-03 15:19
This is probably due to Qt's way of hard coding paths.
Try one of these:
1. Delete everything, clone & build from scratch (bad .pro file)
2. Don't use paths with spaces in between : ~my path~  my_path
3. Follow the [wiki](https://github.com/xaos-project/XaoS/wiki/Developer's-Guide#build-instructions)

**Comment by PiotrNestor** [comment] 2020-06-04 11:10
Yes, building from scratch worked better. Thanks!

**Comment by kanurag94** [comment] 2020-06-04 12:46
:) Closing this issue. Please feel free to reopen in case the issue isn't solved.

For discussions regarding XaoS join https://groups.google.com/forum/#!forum/xaos-users

**Closed by kanurag94** 2020-06-04 12:46 UTC
Labels: documentation, question
