### ISSUE TITLE
macOS app has missing version information

### ISSUE THREAD

**Issue by vitorgalvao** [xaos-project/XaoS#223] opened 2021-10-22 15:59 UTC
**Describe the bug**

To accurately display version information, macOS apps need to have the `CFBundleVersion` and `CFBundleShortVersionString` tags in `Info.plist`.

In XaoS, the keys are missing.

**To Reproduce**

Inspect `XaoS.app/Contents/Info.plist` and verify the keys are missing.

**Expected behavior**

App should have versions.

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser: N/A
 - Version: Any

**Smartphone (please complete the following information):**

N/A

**Additional context**

Alternatively to setting versions during the build process, they can be added after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist"
```

That would use the same version number for both fields. Technically they should be different, but that’s a secondary concern. An accurate version number is important for macOS to know which app to open in ambiguous situations; for users who expect the information available via the Finder; and for interoperability with other apps.

**Comment by core-code** [comment] 2021-12-07 16:03
i can reproduce the issue. any fix forthcoming?

**Comment by kanurag94** [comment] 2021-12-07 16:21
@vitorgalvao Thanks for reporting. I was also able to reproduce the issue. I'll try to fix this in next minor release

**Comment by kanurag94** [comment] 2021-12-07 16:28
Closing since this will be tracked on #210 
Kindly reopen if this is still an issue

**Closed by kanurag94** 2021-12-07 16:28 UTC
Labels: bug, duplicate
