### ISSUE TITLE
Cyrillic problem

### ISSUE THREAD

**Issue by glixx** [xaos-project/XaoS#100] opened 2019-04-18 00:25 UTC
![Screenshot_20190417_235232](https://user-images.githubusercontent.com/2681872/56328884-a64d2c00-6189-11e9-854e-6db18820cd38.png)

**Comment by jblang** [comment] 2019-04-19 03:11
It's because the built-in font only supports Latin characters. The GTK+ GUI has TrueType font support, so it should be able to display Cyrillic correctly.  The GTK+ GUI can be compiled with a configure flag according to instructions in INSTALL.md. 

Also, the Qt GUI has truetype font support but I haven't tried to get i18n to work with Qt yet.  It has its own Qt Linguist instead of Gettext but it can import po files.  It works similarly to gettext in the code, wrapping strings with tr("string").  I think we could probably include the correct Qt header file that defines tr in config.h and `#define gettext tr` to use Qt's library instead of gettext.  There is some documentation [here](https://doc.qt.io/qt-5/internationalization.html).

Ultimately I would like to use Qt as the GUI on all platforms so I can stop maintaining separate GUIs for each platform and I can use more advanced GUI features that Qt provides.

**Comment by glixx** [comment] 2019-04-19 03:47
Qt has context, but your PO files are without context. So importing PO files will not have effect.

But it's good to go by Qt way only. I suggest to you to use transifex.com for translations. It's free for open source projects.
Just create project there. Upload POT file and PO files.
Configure settings of transifex to use translation memory.
When you will upload blank.ts file there transifex will fill all TS files automatically based on PO files (context does not have matter for this task).
As a result you will have online translations and TS files from PO files.

> It's because the built-in font only supports Latin characters

Is it possible to change built-in font?

**Comment by jblang** [comment] 2019-04-19 04:04
The fonts are bitmap fonts defined in C like [this one](https://github.com/xaos-project/XaoS/blob/master/src/filter/font.c).  You would have to find a bitmap font in C format or use something to convert it. It would probably need to use the legacy 8-bit encoding for Cyrillic instead of Unicode.  The [xprint](https://github.com/xaos-project/XaoS/blob/master/src/filter/grlib.c#L405) routine uses iconv to convert the strings from UTF-8 to ISO-8859-1 or 2 before displaying them.  All of the currently supported languages use one of these two encodings.

**Comment by jblang** [comment] 2019-04-19 05:19
I confirmed that it is displayed properly in the GTK+ GUI driver.

**Comment by glixx** [comment] 2019-04-19 06:23
You can save PO file as 8bit encoding if you need.

**Comment by jblang** [comment] 2019-04-20 02:45
That shouldn't be necessary; all the other po files are in UTF-8 and we convert them to 8-bit encoding on the fly. We would just need another conditional for the correct encoding. ISO-8859-5,  i think?

**Comment by glixx** [comment] 2019-04-20 04:24
Any ISO-8859-5, KOI8-R, IBM866 (CP866), CP-1251

**Comment by jblang** [comment] 2019-05-03 01:32
Next release should be based on one of the UIs supporting TrueType so I don't think I want to try to make a bitmap font for it.  I am working on the GTK and Qt UI which support Cyrillic via Truetype fonts and I have already got separate issues for those, so I will close this now.

**Closed by jblang** 2019-05-03 01:32 UTC
Labels: bug, gui
